# Generated by Django 3.2.4 on 2023-02-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='file',
        ),
    ]
